# Use official Java 21 image
FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Build the application
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

# Expose Render port
EXPOSE 8080

# Run application
CMD ["java", "-jar", "target/bookstore-0.0.1-SNAPSHOT.jar"]
